name: Build

on:
  [push, pull_request]

jobs:
  focal-build:
    runs-on: ubuntu-20.04
    container: 
      image: pllee4/ubuntu-ci:20.04-C20
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: mkdir build && cd build && cmake .. && cmake --build .